### ISSUE TITLE
Integration with a vector db for rag ?

### ISSUE THREAD

**Issue by quantumalchemy** [joaomdmoura/crewAI#138] opened 2024-01-15 17:02 UTC
is there a plan to integrate this tool -- for a vector database ie chroma db?

**Comment by EmmaWebGH** [comment] 2024-01-20 08:16
I came here searching for this same thing - how to use RAG with CrewAI.
EG, we have a team of specialist agents... well maybe we should also give them some special knowledge via RAG?

Above solution is a possibility (I have yet to try myself).
But wondering if there could also be a plan to have the ability for RAG for the agents to be integrated natively also.

**Comment by joaomdmoura** [comment] 2024-01-21 16:32
Yes, I'm currently working on the UI and native RAG 😎👉👉  closing this as it's duplicate of #18 for now

**Closed by joaomdmoura** 2024-01-21 16:32 UTC
Labels: question
