### ISSUE TITLE
Manage different output formats for each task??

### ISSUE THREAD

**Issue by cielonet** [joaomdmoura/crewAI#147] opened 2024-01-17 03:33 UTC
Is there currently a way to manage the tasks so that for each output/response by the agent/s of that task I can designate a pydantic base model/class as a partial_variable perhaps to the prompt template?

Here: [langchain output parser](https://python.langchain.com/docs/modules/model_io/output_parsers/types/pydantic#:~:text=This%20output%20parser%20allows%20users,to%20generate%20well%2Dformed%20JSON.)

For example:
task1 -> output is a desired data structure (i.e. pydantic base model)
task2 -> input is a formatted/parsed* response from task1 -> output is another desired data structure

*the input to task2 could even be a value (str,list) from a field/parameter from parsed output(model_dump_json()) in task1?

Thank you.

**Comment by zholti** [comment] 2024-01-17 11:03
I like how [Instructor](https://jxnl.github.io/instructor/) approached this - patching the OpenAI client, adding a `response_model` parameter, and encapsulating all the validation logic in that patched client.

**Comment by joaomdmoura** [comment] 2024-01-21 19:32
Love it, I really like the Instructor approach as well, maybe we could use them in here 🤔  marking as feature accepted

**Comment by joaomdmoura** [comment] 2024-01-21 19:48
seems duplicate of #160 so I'm closing this in favor of that but still planning on exploring instructor

**Closed by joaomdmoura** 2024-01-21 19:48 UTC
Labels: feature-accepted
