### ISSUE TITLE
Support GPT4V Agents

### ISSUE THREAD

**Issue by Ir1d** [joaomdmoura/crewAI#51] opened 2024-01-05 01:10 UTC
Currently, the system seems to only support text-based agents, would be nice to add support for multimodal models.

Autogen's implementation: https://github.com/microsoft/autogen/blob/main/autogen/agentchat/contrib/multimodal_conversable_agent.py

It seems non-straightforward to make the langchain memory modules to support multi-modal memory. Is my understanding correct?

**Comment by joaomdmoura** [comment] 2024-01-21 03:32
We are def going multimodel, we can work around memory and build our internal one if that becomes a blocker, addin this as feature-accepted

**Comment by joaomdmoura** [comment] 2024-01-21 03:38
closing this as duplicate of #114

**Closed by joaomdmoura** 2024-01-21 03:38 UTC
Labels: feature-request, feature-accepted
